# Generated by Django 4.2.13 on 2024-05-23 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('hot_water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cold_water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sewage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cold_water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sewage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
