# Generated by Django 4.2.13 on 2024-05-26 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usage',
            name='month',
        ),
    ]
