# Generated by Django 4.2.13 on 2024-05-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_usage_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], default='RUB', max_length=3),
        ),
    ]
