# Generated by Django 4.2.13 on 2024-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_rates_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='sewage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
