# Generated by Django 4.2.13 on 2024-05-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_usage_sewage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='month',
            field=models.DateField(),
        ),
    ]
