# Generated by Django 4.2.13 on 2024-05-27 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_usage_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='auto_calculate_sewage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usage',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='usage',
            name='sewage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
